version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Restore started on `date`
      - npm install
      - mv src/store/config-dev.js src/store/config.js
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - mv appspec-dev.yml appspec.yml
artifacts:
  files:
    - 'dist/**/*'
    - 'appspec.yml'
    
